### PR TITLE
Move appear life cycle to placeholder

### PR DESCRIPTION
**Pull request by onevcat**
And also ensure image setting on main thread

### CODE REVIEW

**Comment by onevcat** [comment]
This is a workaround for #1508. But a real fix is still being waited from Apple.

**Comment by hyouuu** [comment]
Please revert this change as it causes flickering every time swiftUI re-renders - see details at https://github.com/onevcat/Kingfisher/issues/1549

**Comment by hyouuu** [comment]
@onevcat ^

**Comment by onevcat** [comment]
@hyouuu This fix was intended as a workaround of Apple's bug on iOS 14. However, the flickering seems to be a side effect. I will see how we can solve it.

**Comment by hyouuu** [comment]
@onevcat yes the intention is well understood and appreciated - it's just the side effect is too much :) Hope you can find a more appropriate fix soon and thanks!

**Pull request merged**
