### PR TITLE
Swift 2.3 compatibility updates

### PR DESCRIPTION
**Pull request by andreyz**
Fixed compilation errors with Swift 2.3 toolchain.

### CODE REVIEW

**Comment by macecchi** [comment]
Thanks for sharing that 👍 
You can also update the Xcode version in `.travis.yml` to `xcode8` (line 3) to make the Travis CI bot build correctly.

**Comment by onevcat** [comment]
The master branch is now for Swift 2.2, and there is a plan to jump to Swift 3 later.

There should be not so much change needed for Swift 2.3, so it would be fine to setup a swift2.3 branch later for back compatibility.

I will open a swift 2.3 branch later.
@andreyz Would you mind to open another p-r for that branch? Thanks.

**Comment by onevcat** [comment]
And of course it would be great help if you can change the travis setting to make test passing.

**Comment by macecchi** [comment]
I've created another fork with the updated Xcode image but there are some other issues. The other targets (for macOS etc) haven't added the legacy swift flag and there are some other sdk changes. I'm working on them :)

**Comment by macecchi** [comment]
I just pushed a PR (#367) with the Swift 2.3 version working with all targets and all tests passing.

**Comment by onevcat** [comment]
Amazing! No problem with the CI errors, I will trigger them again and confirm everything goes well before merging.

Great work! Thank you for your contributing.

**Comment by andreyz** [comment]
Closing this, given that [PR 367](https://github.com/onevcat/Kingfisher/pull/367) supersedes this one.

**Pull request closed without merging**
