### PR TITLE
Handle Redirect URL

### PR DESCRIPTION
**Pull request by tengpeng**

### CODE REVIEW

**Comment by onevcat** [comment]
@tengpeng 
Hi, thanks for considering to contribute.

The redirected url support is a feature in plan and I am appreciated that you did a implementation for it. However, this p-r could not be merged since it changed the file format and coding style so much.

I understand that it might be caused without noticing and by a script. But would you mind to just add the url redirecting things, without changing the file access mode and/or indent of files? I will take a look at it once there is another p-r for it!

Thanks.

**Comment by tengpeng** [comment]
Thanks for reviewing. I suppose the indent is changed by default ctrl + I in Xcode 8, since I don't use swiftLint. I'll try to revert such changes.

On file access mode, can you give me an example? I am not sure what could be improved or prevented.  Thanks.

**Comment by onevcat** [comment]
@tengpeng 

Hi, it seems you are changing all files to 755. See the screenshot below:

snip20160920_1

You can also check it in the "Files changed" tab in this page.

**Comment by lucasecf** [comment]
Hello @onevcat , if I may ask, was the redirected url support ever implemented? Couldn't find any references besides this closed issue.

**Comment by aehlke** [comment]
I can only find a redirect handler callback, but I don't think it introduces redirection handling, just provides an injection point. I'm also unclear on this

**Comment by onevcat** [comment]
You can access the session, redirected request, modify the request and tell the downloader how to continue. Basically you can do things like:

```swift
KFImage.url(url)
  .redirectHandler { payload in
    var redirected = payload.newRequest
    redirected.setValue("some value", forHTTPHeaderField: "in_header")
    payload.completionHandler(redirected)
  }
```

**Pull request closed without merging**
