### PR TITLE
added an attribute to fix error on mac catalyst

### PR DESCRIPTION
**Pull request by kvyatkovskys**
Hello. I have the bug on Mac catalyst. Added a little bit fix

Screenshot 2021-04-21 at 11 25 31

### CODE REVIEW

**Comment by onevcat** [comment]
@kvyatkovskys Thanks for this. May I know the Xcode version you are using? I guess it is more likely a compiler version issue and I want to reproduce it.

**Comment by kvyatkovskys** [comment]
> @kvyatkovskys Thanks for this. May I know the Xcode version you are using? I guess it is more likely a compiler version issue and I want to reproduce it.

sure, we use `Xcode Version 12.0 (12A7209)` for our Mac catalyst project

**Comment by onevcat** [comment]
Umm, I guess it is a change in Swift 5.3.1 (Xcode 12.2). I guess it should be no harm to add the tag explicitly,. I will download an older version of Xcode and verify the fix. Stay tuned!

**Comment by onevcat** [comment]
I tried Xcode 12.0 and 12.1, but without reproducing this issue. That is weird. 

I guess it should be no harm to add the `@ViewBuilder` annotation here, but I am really curious on what is going on.

Do you have any chance to try clean the project and build again?

**Comment by kvyatkovskys** [comment]
Very strange 🤔
Yep, cleaned the project... Reproduced every time for me 😕

**Comment by onevcat** [comment]
Anyway, let's merge it and see what could happen. Thanks!

**Pull request merged**
