### PR TITLE
Update Kingfisher.swift

### PR DESCRIPTION
**Pull request by honbolau**
Remove redundant code

### CODE REVIEW

**Comment by onevcat** [comment]
@honbolau Thanks for the PR.

But I didn't see a good reason for this change. Since the `KingfisherCompatible` is a public protocol, this change at last breaks the compatibility (although it probably no one is trying to conform to it) somehow.

Maybe it brings minor performance improvement since it gets rid of the dynamic dispatch. But it should be almost ignorable. How do you think about it?

**Comment by honbolau** [comment]
If ` kf ` was rewritten by other users, so what's the meaning of other users to rewrite this property? What can you do after rewriting? ` kf ` type for ` Kingfisher `, defined as follows. With a final class like this, you cannot create a SubClass, so you cannot add an stored property directly. If only add computed property and associated property and method, don't have to fully implement a ` kf ` properties.

**Comment by honbolau** [comment]
Feel free to close this PR if it not necessary. 😂

**Comment by onevcat** [comment]
@honbolau 😂

I'd like to merge it, but not for version 4. Could you make the same change and send a pull request to branch 5.0? I think we could contain this change in the new major update version.

**Pull request closed without merging**
