### PR TITLE
Progressive JPEG

### PR DESCRIPTION
**Pull request by lixiang1994**

### CODE REVIEW

**Comment by onevcat** [comment]
@lixiang1994 Thanks for these commits. I didn't get a time for it now, but feel free to let me know if you get to a milestone so I can start to have a look at it as soon as possible!

**Comment by lixiang1994** [comment]
@onevcat 👌 I think it is ok.

**Comment by onevcat** [comment]
@lixiang1994 It is fantastic at a brief look and just works like magic!

I will create a PR to your master branch later with some obvious changes, then let's check some details before we can merge and release it.

**Comment by onevcat** [comment]
LGTM so far. Thanks for these commits.

I guess we can release progressive support as a beta for now, during the while, we still need to improve the quality, add necessary tests and write documentation for it. 

But it is another story, this PR is large enough and good to be merged.

**Comment by lixiang1994** [comment]
😘

**Pull request merged**
