### PR TITLE
修复各种扩展中`taskIdentifier`的线程安全问题 它在不同线程中调用可能出现崩溃问题

### PR DESCRIPTION
**Pull request by lixiang1994**
可用类似代码模拟场景复现, 该问题是通过Bugly收集到的
image

### CODE REVIEW

**Comment by onevcat** [comment]
These extension methods belong to the UI part, and they are not designed as thread-safe methods. 

Similar to the UIKit things, you need to make sure to call them from the main thread to keep all accessing safe.

**Comment by lixiang1994** [comment]
`onShouldApply`闭包中使用了`taskIdentifier`, `onShouldApply`可能在任何线程被调用

**Comment by lixiang1994** [comment]
或者需要确保`onShouldApply`只在主线程内调用, 你更倾向于哪一种?

**Comment by lixiang1994** [comment]
@onevcat ??? 怎么说

**Comment by onevcat** [comment]
It makes sense. But several concerns:

1. Why you didn't add lock in the setter of `ImageView` and `NSButton` extensions. Should we also need lock it in the identifier setter?
2. Can you remove the `DevelopmentTeam` changing from the PR?

**Comment by lixiang1994** [comment]
`objc_getAssociatedObject`和`objc_setAssociatedObject`是线程安全的.
`AssociationsManager `通过持有一个自旋锁`spinlock_t`保证对`AssociationsHashMap`的操作是线程安全的, 即每次只会有一个线程对`AssociationsHashMap`进行操作.
我们的问题是`Box`中的`value`并不是线程安全的, 所以只需要在`value`相关操作时增加锁就可以了.

**Comment by lixiang1994** [comment]
🐱喵喵喵~

**Pull request merged**
