### PR TITLE
new image processors: blend, compositing

### PR DESCRIPTION
**Pull request by yemodin**
Adds blending/compositing(macOS) processors. Allows easily blend/compositing.

For example, I was needed to blend unedited images which have the different background color so they will appear blended with the background color of my interface.

### CODE REVIEW

**Comment by yemodin** [comment]
Also, I changed macOS version to 10.11 to successfully build and run.

**Comment by onevcat** [comment]
@yemodin Looks great.

However, if we increase the minimal deploy target, we have to release another major update since it breaks compatibility. May I know which API you are using is 10.11 above?

And do not worry about the failing tests. If we could add this processor to the framework, I will check and fix these tests.

**Comment by yemodin** [comment]
@onevcat I changed only demo project target, not framework target. Next lines of macOS demo require 10.11+:

**Comment by yemodin** [comment]
Also, I added the test to each image processor. And made the pull request for image assets:
https://github.com/onevcat/Kingfisher-TestImages/pull/1

**Comment by onevcat** [comment]
Oh, cool! I will check it now.

**Pull request merged**
