### PR TITLE
Support animated images in SwiftUI

### PR DESCRIPTION
**Pull request by Binlogo**
Solves: #1657

### CODE REVIEW

**Comment by onevcat** [comment]
Oh! You are really fast. Thank you so much!

I am not sure if all these things are supported in the animated image view, since it is so different from a normal image view and I expected a very simple wrapper just around the `AnimatedImageView`. But I will take a look at your implementation and see if all work.

Good job!

**Comment by Binlogo** [comment]
Got your point. If just a single wrapper, it can hardly interact with other view or do other operations. 

I see a better implementation is on the go in your mind. 👀 Expect to take some improve advice.

⚠️ By the way, an known issue: after setting a processor, the processor works as expected, but animated image would be static.

**Comment by onevcat** [comment]
It seems to be a few code duplication. I've done some refactoring and opened #1705 for the future work. @Binlogo  Thanks for providing this starting point and adding this nice feature!

**Comment by buluoray** [comment]
Does 6.3.x support KFAnimatedView?

**Comment by onevcat** [comment]
No. It is a feature added in 7.0, which is currently in beta.

**Pull request merged**
