### PR TITLE
Swift 4 Support

### PR DESCRIPTION
**Pull request by onevcat**

### CODE REVIEW

**Comment by lfarah** [comment]
@onevcat when are you merging this? Would love to continue using Kingfisher in my project!
screen shot 2017-07-18 at 11 46 03 am

**Comment by onevcat** [comment]
@lfarah It will not be merged until Swift 4 officially released. Before that, you could just use the "swift4" branch to continue use Kingfisher is your Swift 4 project.

**Comment by lightsprint09** [comment]
Hey. There is an issues withe carthage and the new build system. Would it be ok to revert to the old build system??

**Comment by onevcat** [comment]
@lightsprint09 
Fallback to legacy build system/

**Comment by hprobotic** [comment]
I faced with 3 errors:
```
- /Users/johnp/Project/Inspirar/Pods/Kingfisher/Sources/ImageView+Kingfisher.swift:230:2: @objc cannot be applied to this declaration
- /Users/johnp/Project/Inspirar/Pods/Kingfisher/Sources/Filter.swift:74:38: Value of type 'CIImage' has no member 'cropped'
/Users/johnp/Project/Inspirar/Pods/Kingfisher/Sources/Filter.swift:88:53: Incorrect argument label in call (have '_:parameters:', expected '_:withInputParameters:')
```
I using xcode 9, swift 4

**Pull request merged**
