### PR TITLE
Fix SPM errors in Xcode 11

### PR DESCRIPTION
**Pull request by dstranz**
As described in issue #1221 iOS app is unable to build because AppKit, UIKit and WatchKit wasn't conditionally imported in source files. I added `canImport` when it was necessary.

I need to add `platforms` to `Package.swift` to tell Xcode that it can use iOS 10 as development target for Kingfisher and fix a lot of "not available" errors.

### CODE REVIEW

**Comment by onevcat** [comment]
Maybe it is duplicated to #1209 ?

The related changes are now under xcode11 branch.

**Comment by dstranz** [comment]
@onevcat I missed that branches.

Personally I think it's better to use enum in platforms rather than strings:
`platforms: [.iOS("10.0"), .macOS("10.12"), .tvOS("10.0"), .watchOS("3.0")],`
vs
`platforms: [.iOS(.v10), .macOS(.v10_12), .tvOS(.v10), .watchOS(.v3)],`

and  `canImport` rather than `#if os(macOS)` but booth are will works fine.

**Comment by onevcat** [comment]
@dstranz Oh, I agree with you! Can you instead send a PR to that branch? Big thanks!

**Comment by dstranz** [comment]
@onevcat There are some other changes from master included in my branch - is it fine or should I create another branch from xcode11?

**Comment by onevcat** [comment]
Yes, I suggest a new branch based on xcode11!

**Comment by dstranz** [comment]
Reopened as #1223

**Pull request closed without merging**
