### PR TITLE
Force iOS v14 in order to compile

### PR DESCRIPTION
**Pull request by netbe**
Hi, 

I was trying the StateObject branch but encounter issues when compiling with xcodebuild. The Package.swift needed to be updated in order to work.

FYI: There's still a warning related to the Info.plist file but compilation works anyway

```
found 1 file(s) which are unhandled; explicitly declare them as resources or exclude from the target
[16:19:34]: ▸     /Users/netbe/Library/Developer/Xcode/DerivedData/Luce-gntixnwxpyznsygtuscsasjvlyxc/SourcePackages/checkouts/Kingfisher/Sources/Info.plist
[16:19:35]: ▸ ignoring declared target(s) 'swift-nio-zlib-support' in the system package
```

### CODE REVIEW

**Comment by onevcat** [comment]
It should not be required since all the related types are marked with availability of iOS 14. Basically you only need the deploy target of your own project to iOS 14 to adopt to the `@StateObject` based KFImage.

Can you make sure that you have upgraded your app deploy target? And it is also helpful if I know the compiling error you were having.

**Comment by netbe** [comment]
You're right, I thought the same, but our project targets ios 14.0+... this only happens in the CI, note the following param passed to xcodebuild `-disableAutomaticPackageResolution`

Here's the log part where the errors occured:

```
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/ImageBinder.swift:35:24: [31mcannot find type 'ObservableObject' in scope[0m
[14:36:43]: ▸ [35m    class ImageBinder: ObservableObject {[0m
[14:36:43]: ▸ [35m[36m                       ^~~~~~~~~~~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/ImageBinder.swift:50:23: [31mcannot find type 'Binding' in scope[0m
[14:36:43]: ▸ [35m        var isLoaded: Binding<Bool>[0m
[14:36:43]: ▸ [35m[36m                      ^~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/ImageBinder.swift:52:9: [31munknown attribute 'Published'[0m
[14:36:43]: ▸ [35m        @Published var loaded = false[0m
[14:36:43]: ▸ [35m[36m        ^[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/ImageBinder.swift:53:9: [31munknown attribute 'Published'[0m
[14:36:43]: ▸ [35m        @Published var loadedImage: KFCrossPlatformImage? = nil[0m
[14:36:43]: ▸ [35m[36m        ^[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/ImageBinder.swift:56:80: [31mcannot find type 'Binding' in scope[0m
[14:36:43]: ▸ [35m        init(source: Source?, options: KingfisherOptionsInfo? = nil, isLoaded: Binding<Bool>) {[0m
[14:36:43]: ▸ [35m[36m                                                                               ^~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/ImageBinder.swift:68:41: [31mcannot find type 'Binding' in scope[0m
[14:36:43]: ▸ [35m        init(source: Source?, isLoaded: Binding<Bool>) {[0m
[14:36:43]: ▸ [35m[36m                                        ^~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageProtocol.swift:31:34: [31mcannot find type 'View' in scope[0m
[14:36:43]: ▸ [35mpublic protocol KFImageProtocol: View, KFOptionSetter {[0m
[14:36:43]: ▸ [35m[36m                                 ^~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/ImageBinder.swift:109:56: [31mcannot find 'Animation' in scope[0m
[14:36:43]: ▸ [35m                                    .map { duration in Animation.linear(duration: duration) }[0m
[14:36:43]: ▸ [35m[36m                                                       ^~~~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/ImageBinder.swift:110:33: [31mcannot find 'withAnimation' in scope[0m
[14:36:43]: ▸ [35m                                withAnimation(animation) { self.loaded = true }[0m
[14:36:43]: ▸ [35m[36m                                ^~~~~~~~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageProtocol.swift:100:37: [31mcannot find type 'View' in scope[0m
[14:36:43]: ▸ [35mpublic protocol KFImageHoldingView: View {[0m
[14:36:43]: ▸ [35m[36m                                    ^~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/ImageContext.swift:36:26: [31mcannot find type 'AnyView' in scope[0m
[14:36:43]: ▸ [35m        var placeholder: AnyView? = nil[0m
[14:36:43]: ▸ [35m[36m                         ^~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageProtocol.swift:33:26: [31mtype 'Self.HoldingView' does not conform to protocol 'KFImageHoldingView'[0m
[14:36:43]: ▸ [35m    var context: KFImage.Context<HoldingView> { get set }[0m
[14:36:43]: ▸ [35m[36m                         ^[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageProtocol.swift:34:27: [31mtype 'Self.HoldingView' does not conform to protocol 'KFImageHoldingView'[0m
[14:36:43]: ▸ [35m    init(context: KFImage.Context<HoldingView>)[0m
[14:36:43]: ▸ [35m[36m                          ^[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFAnimatedImage.swift:48:37: [31mcannot find type 'Context' in scope[0m
[14:36:43]: ▸ [35m    public func makeUIView(context: Context) -> AnimatedImageView {[0m
[14:36:43]: ▸ [35m[36m                                    ^~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFAnimatedImage.swift:58:68: [31mcannot find type 'Context' in scope[0m
[14:36:43]: ▸ [35m    public func updateUIView(_ uiView: AnimatedImageView, context: Context) {[0m
[14:36:43]: ▸ [35m[36m                                                                   ^~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFAnimatedImage.swift:41:47: [31mcannot find type 'UIViewRepresentable' in scope[0m
[14:36:43]: ▸ [35mpublic struct KFAnimatedImageViewRepresenter: UIViewRepresentable, KFImageHoldingView {[0m
[14:36:43]: ▸ [35m[36m                                              ^~~~~~~~~~~~~~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImage.swift:32:33: [31mcannot find type 'Image' in scope[0m
[14:36:43]: ▸ [35m    public var context: Context<Image>[0m
[14:36:43]: ▸ [35m[36m                                ^~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImage.swift:33:34: [31mcannot find type 'Image' in scope[0m
[14:36:43]: ▸ [35m    public init(context: Context<Image>) {[0m
[14:36:43]: ▸ [35m[36m                                 ^~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImage.swift:31:15: [31mtype 'KFImage' does not conform to protocol 'KFImageProtocol'[0m
[14:36:43]: ▸ [35mpublic struct KFImage: KFImageProtocol {[0m
[14:36:43]: ▸ [35m[36m              ^[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImage.swift:39:11: [31mcannot find type 'Image' in scope[0m
[14:36:43]: ▸ [35mextension Image: KFImageHoldingView {[0m
[14:36:43]: ▸ [35m[36m                   ^[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImage.swift:50:20: [31mcannot find type 'EdgeInsets' in scope[0m
[14:36:43]: ▸ [35m        capInsets: EdgeInsets = EdgeInsets(),[0m
[14:36:43]: ▸ [35m[36m          ^~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImage.swift:51:23: [31mcannot find type 'Image' in scope[0m
[14:36:43]: ▸ [35m        resizingMode: Image.ResizingMode = .stretch) -> KFImage[0m
[14:36:43]: ▸ [35m[36m                   ^~~~~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImage.swift:56:48: [31mcannot find type 'Image' in scope[0m
[14:36:43]: ▸ [35m    public func renderingMode(_ renderingMode: Image.TemplateRenderingMode?) -> KFImage {[0m
[14:36:43]: ▸ [35m[36m                      ^~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImage.swift:60:48: [31mcannot find type 'Image' in scope[0m
[14:36:43]: ▸ [35m    public func interpolation(_ interpolation: Image.Interpolation) -> KFImage {[0m
[14:36:43]: ▸ [35m[36m                                               ^~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImage.swift:83:83: [31mcannot find type 'Binding' in scope[0m
[14:36:43]: ▸ [35m    public init(source: Source?, options: KingfisherOptionsInfo? = nil, isLoaded: Binding<Bool> = .constant(false)) {[0m
[14:36:43]: ▸ [35m[36m                                               ^~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImage.swift:99:72: [31mcannot find type 'Binding' in scope[0m
[14:36:43]: ▸ [35m    init(_ url: URL?, options: KingfisherOptionsInfo? = nil, isLoaded: Binding<Bool> = .constant(false)) {[0m
[14:36:43]: ▸ [35m[36m                                                                                  ^~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImage.swift:53:9: [31mtype of expression is ambiguous without more context[0m
[14:36:43]: ▸ [35m        configure { $0.resizable(capInsets: capInsets, resizingMode: resizingMode) }[0m
[14:36:43]: ▸ [35m[36m                                                                       ^~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImage.swift:57:9: [31mtype of expression is ambiguous without more context[0m
[14:36:43]: ▸ [35m        configure { $0.renderingMode(renderingMode) }[0m
[14:36:43]: ▸ [35m[36m        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImage.swift:61:9: [31mtype of expression is ambiguous without more context[0m
[14:36:43]: ▸ [35m        configure { $0.interpolation(interpolation) }[0m
[14:36:43]: ▸ [35m[36m        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImage.swift:65:19: [31mcannot convert value of type '(_) -> _' to expected argument type '(KFImage.HoldingView) -> KFImage.HoldingView'[0m
[14:36:43]: ▸ [35m        configure { $0.antialiased(isAntialiased) }[0m
[14:36:43]: ▸ [35m[36m        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImage.swift:65:24: [31mcannot convert value of type '_' to closure result type 'KFImage.HoldingView'[0m
[14:36:43]: ▸ [35m        configure { $0.antialiased(isAntialiased) }[0m
[14:36:43]: ▸ [35m[36m                  ^[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageProtocol.swift:70:44: [31mcannot find type 'Binding' in scope[0m
[14:36:43]: ▸ [35m    public init(source: Source?, isLoaded: Binding<Bool> = .constant(false)) {[0m
[14:36:43]: ▸ [35m[36m                    ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageProtocol.swift:81:40: [31mcannot find type 'Binding' in scope[0m
[14:36:43]: ▸ [35m    public init(_ url: URL?, isLoaded: Binding<Bool> = .constant(false)) {[0m
[14:36:43]: ▸ [35m[36m                                           ^~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageOptions.swift:42:38: [31mcannot find type 'Binding' in scope[0m
[14:36:43]: ▸ [35m        _ source: Source?, isLoaded: Binding<Bool> = .constant(false)[0m
[14:36:43]: ▸ [35m[36m                                       ^~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageOptions.swift:56:42: [31mcannot find type 'Binding' in scope[0m
[14:36:43]: ▸ [35m        _ resource: Resource?, isLoaded: Binding<Bool> = .constant(false)[0m
[14:36:43]: ▸ [35m[36m                                     ^~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageOptions.swift:72:57: [31mcannot find type 'Binding' in scope[0m
[14:36:43]: ▸ [35m        _ url: URL?, cacheKey: String? = nil, isLoaded: Binding<Bool> = .constant(false)[0m
[14:36:43]: ▸ [35m[36m                                         ^~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageOptions.swift:86:51: [31mcannot find type 'Binding' in scope[0m
[14:36:43]: ▸ [35m        _ provider: ImageDataProvider?, isLoaded: Binding<Bool> = .constant(false)[0m
[14:36:43]: ▸ [35m[36m                                                        ^~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageOptions.swift:101:52: [31mcannot find type 'Binding' in scope[0m
[14:36:43]: ▸ [35m        _ data: Data?, cacheKey: String, isLoaded: Binding<Bool> = .constant(false)[0m
[14:36:43]: ▸ [35m[36m                                                  ^~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageOptions.swift:117:38: [31mcannot find type 'View' in scope[0m
[14:36:43]: ▸ [35m    public func placeholder<Content: View>(@ViewBuilder _ content: () -> Content) -> Self {[0m
[14:36:43]: ▸ [35m[36m                                                   ^~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageOptions.swift:117:44: [31munknown attribute 'ViewBuilder'[0m
[14:36:43]: ▸ [35m    public func placeholder<Content: View>(@ViewBuilder _ content: () -> Content) -> Self {[0m
[14:36:43]: ▸ [35m[36m                                     ^~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageOptions.swift:120:38: [31mcannot find 'AnyView' in scope[0m
[14:36:43]: ▸ [35m        result.context.placeholder = AnyView(v)[0m
[14:36:43]: ▸ [35m[36m                                           ^[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageOptions.swift:142:46: [31mcannot infer contextual base in reference to member 'fade'[0m
[14:36:43]: ▸ [35m        context.binder.options.transition = .fade(duration)[0m
[14:36:43]: ▸ [35m[36m                                     ^~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageProtocol.swift:39:27: [31mcannot find type 'View' in scope[0m
[14:36:43]: ▸ [35m    public var body: some View {[0m
[14:36:43]: ▸ [35m[36m                                            ~^~~~~~~~~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageProtocol.swift:86:36: [31mtype 'Self.HoldingView' does not conform to protocol 'KFImageHoldingView'[0m
[14:36:43]: ▸ [35m        self.init(context: KFImage.Context<HoldingView>(binder: binder))[0m
[14:36:43]: ▸ [35m[36m                          ^~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageRenderer.swift:39:22: [31mcannot find type 'AnyView' in scope[0m
[14:36:43]: ▸ [35m    var placeholder: AnyView?[0m
[14:36:43]: ▸ [35m[36m                                   ^[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageRenderer.swift:36:5: [31munknown attribute 'StateObject'[0m
[14:36:43]: ▸ [35m    @StateObject var binder: KFImage.ImageBinder[0m
[14:36:43]: ▸ [35m[36m                     ^~~~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageRenderer.swift:49:20: [31mcannot find type 'View' in scope[0m
[14:36:43]: ▸ [35m    var body: some View {[0m
[14:36:43]: ▸ [35m[36m    ^[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageRenderer.swift:48:5: [31munknown attribute 'ViewBuilder'[0m
[14:36:43]: ▸ [35m    @ViewBuilder[0m
[14:36:43]: ▸ [35m[36m                   ^~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageRenderer.swift:33:39: [31mcannot find type 'View' in scope[0m
[14:36:43]: ▸ [35mstruct KFImageRenderer<HoldingView> : View where HoldingView: KFImageHoldingView {[0m
[14:36:43]: ▸ [35m[36m    ^[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageRenderer.swift:85:11: [31mcannot find type 'Image' in scope[0m
[14:36:43]: ▸ [35mextension Image {[0m
[14:36:43]: ▸ [35m[36m                                      ^~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageRenderer.swift:99:25: [31mcannot find type 'Image' in scope[0m
[14:36:43]: ▸ [35m    func toSwiftUI() -> Image.Orientation {[0m
[14:36:43]: ▸ [35m[36m          ^~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageRenderer.swift:55:18: [31mvalue of type 'HoldingView' has no member 'opacity'[0m
[14:36:43]: ▸ [35m                .opacity(binder.loaded ? 1.0 : 0.0)[0m
[14:36:43]: ▸ [35m[36m                        ^~~~~[0m
[14:36:43]: ▸ [35m[31m❌  [0m/usr/local/var/jenkins/Library/Developer/Xcode/DerivedData/Luce-fxupbutvenwvlmfqyvqqwpecyges/SourcePackages/checkouts/Kingfisher/Sources/SwiftUI/KFImageRenderer.swift:57:13: [31mcannot find 'Group' in scope[0m
[14:36:43]: ▸ [35m            Group {[0m
[14:36:43]: ▸ [35m[36m                 ^~~~~~~[0m
[14:36:43]: [35m[33m▸[0m [39;1mProcessing[0m empty.plist[0m
[14:36:43]: [35m[33m▸[0m [39;1mCompiling[0m Keychain.swift[0m
[14:36:43]: [35m[33m▸[0m [39;1mCompiling[0m Keychain.swift[0m
[14:36:43]: ▸ [35m** ARCHIVE FAILED **[0m
```

**Comment by onevcat** [comment]
From the log, it is more likely you are not using the correct version of Xcode or not linking SwiftUI or UIKit (iOS SDK) when you are building Kingfisher at all. If it is only happening on your CI, can it be some configuration on your CI?

**Comment by netbe** [comment]
I am using Xcode 12.4. And for linking SwiftUI or UIKit, I don't see how or why I should do anything in particular.

**Comment by onevcat** [comment]
@netbe I guess I got to know what is going on. It seems we encountered [this issue](https://stackoverflow.com/questions/60073481/my-archive-build-fails-with-error-no-such-module-combine/62085591#62085591).

I just pushed some changes in the `feature/StateObject` branch, can you try and see if it is working now? Thanks!

**Pull request closed without merging**
