### PR TITLE
Resource based api

### PR DESCRIPTION
**Pull request by onevcat**
This pull-request added resource based API for Kingfisher. We could decouple the target URL and the cache key by using this resource APIs. See #93 for more.

### CODE REVIEW

**Comment by Krisiacik** [comment]
Thank you Onevcat! :)

**Comment by RuiAAPeres** [comment]
After merging this work on master, can we also push it to branch `swift-2.0`? Awesome work.

**Comment by onevcat** [comment]
Of course.

**Comment by dmcrodrigues** [comment]
Awesome work, thank you for this!

**Pull request merged**
